### ISSUE TITLE
Making a new summary of conference

### ISSUE THREAD

**Issue by yamathcy** [DmitryRyumin/NewEraAI-Papers#2]
Dear DmitryRyumin,
Thank you for your awesome summary of AI papers and conferences! 

I'm working on Music and AI research, and I'd like to make a summary of the ISMIR conference, which is a leading research conference in the Music and AI field, using your format.
Here, the repository is a WIP one: https://github.com/yamathcy/ISMIR-2023-Papers
(If there is any problem, I will immediately delete it)

Could I add its link to this repository's readme?

Thank you for creating the repository. I appreciate your effort.
yamathcy

**Comment by DmitryRyumin** [comment]
Hi @yamathcy, 👋

Great idea! I added a link to the [ISMIR-2023-Papers](https://github.com/yamathcy/ISMIR-2023-Papers) in all relevant conference repositories, including [CVPR](https://github.com/DmitryRyumin/CVPR-2023-Papers), [ICCV](https://github.com/DmitryRyumin/ICCV-2023-Papers), [ICASSP](https://github.com/DmitryRyumin/ICASSP-2023-Papers), [INTERSPEECH](https://github.com/DmitryRyumin/INTERSPEECH-2023-Papers), and [NewEraAI-Papers](https://github.com/DmitryRyumin/NewEraAI-Papers).

In your [ISMIR repository](https://github.com/yamathcy/ISMIR-2023-Papers), I recommend using badges for all the links. Badges are more informative, providing a quick view of the popularity of repositories associated with the papers (based on the number of stars). Since there aren't many papers at this conference, adding badges to the GitHub readme will not greatly affect loading times and will improve the clarity of information.
